sched: main.cpp Event.cpp Process.cpp scheduler.cpp Simulator.cpp utility.cpp
	g++ -static-libstdc++ -std=c++11 -o sched main.cpp Event.cpp Process.cpp scheduler.cpp Simulator.cpp utility.cpp

clean:
	rm -f sched *~	